fix: reqwest must use blocking client since opentelemetry 0.28 (#220)
I was getting in my local and deployed testing:

```
thread 'OpenTelemetry.Traces.BatchProcessor' panicked at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/ops/function.rs:250:5:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

Checking some searches and other Github discussions, I found [this bug](https://github.com/open-telemetry/opentelemetry-rust/issues/2673) which linked [this doc section](https://github.com/open-telemetry/opentelemetry-rust/blob/main/docs/migration_0.28.md#async-runtime-requirements-removed). It seems only the blocking reqwest client is supported by otlp now. This seems to fix it on my local.